module.exports = {
  Ping: require('./ping'),
  Insult: require('./insult'),
  Info: require('./info'),
  Team: require('./teams'),
  Music: require('./music'),
  Poll: require('./poll'),
  List: require('./list'),
  Help: require('./help'),
  Marvin: require('./marvin'),
  Server: require('./server'),
  Raid: require('./raid'),
  Roster: require('./roster'),
  TurnamentInfo: require('./turnament/info'),
};
