module.exports = {
    csgo: {
        title: 'Counter Strike: Global Offensive',
        thumb: 'https://i.imgur.com/YxR7EhM.jpg',
        image: 'https://i.imgur.com/O4JtrRq.jpg',
        link: 'steam://store/730',
        info: 'Bomb Defusal, 2v2 - 5v5, 5vOnline, Gungame / Team Deathmatch',
        color: '#f69f25',
    },
    tm: {
        title: 'TrackMania Nations Forever',
        thumb: 'https://i.imgur.com/PiUVGGT.jpg',
        image: 'https://i.imgur.com/483zKDe.jpg',
        link: 'steam://store/11020',
        info: 'Crazy Rennen fahren und Rekorde brechen.',
        color: '#088a3f',
    },
    tf2: {
        title: 'Team Fortress 2',
        thumb: 'https://i.imgur.com/tSdyZue.jpg',
        image: 'https://i.imgur.com/z8ozDXX.jpg',
        link: 'steam://store/440',
        info: 'WaterCube Fun Team Deathmatch',
        color: '#ab6c19',
    },
    xo: {
        title: 'Xonotic',
        thumb: 'https://i.imgur.com/iTs5Vho.jpg',
        image: 'https://i.imgur.com/pe0kLzz.jpg',
        link: 'https://xonotic.org/',
        info: 'Arena, 1v1 Turnier, Deathmatch, Capture the Flag',
        color: '#205b9c',
    },
    sc2: {
        title: 'StarCraft 2',
        thumb: 'https://i.imgur.com/Sqd5TPh.jpg',
        image: 'https://i.imgur.com/RdJEbkH.jpg',
        link: 'https://eu.shop.battle.net/de-de/product/starcraft-ii',
        info: 'Alle gegen alle, 2v2 Turnier',
        color: '#96dbf4',
    },
    dota: {
        title: 'DOTA 2',
        thumb: 'https://i.imgur.com/4VN3kni.jpg',
        image: 'https://i.imgur.com/LTnI0T3.jpg',
        link: 'steam://store/570',
        info: '2v2 - 5v5, 5vOnline',
        color: '#d44628',
    },
    spell: {
        title: 'Spellsworn',
        thumb: 'https://i.imgur.com/jUlQzel.jpg',
        image: 'https://i.imgur.com/qGAZQGE.jpg',
        link: 'steam://store/360620',
        info: 'Alle gegen alle Arena',
        color: '#b3f3fc',
    },
    // sol: {
    //     title: 'Soldat',
    //     thumb: 'https://i.imgur.com/H3erAbd.jpg',
    //     link: 'steam://store/638490',
    //     info: 'Für zwischendurch',
    //     color: '#f42319',
    // },
    // rpg: {
    //     title: 'Rollenspiel One-Shots',
    //     thumb: 'https://i.imgur.com/gJFsP1t.jpg',
    //     link: '',
    //     info: 'One-Shot in 2 Etappen',
    //     color: '#cca34e',
    // },
    skr: {
        title: 'Skribbl.io',
        thumb: 'https://i.imgur.com/Kzi9U9g.jpg',
        image: 'https://i.imgur.com/e0IfJn7.jpg',
        link: 'https://skribbl.io/',
        info: 'Browser, Zwischendurch',
        color: '#245195',
    },
    // cah: {
    //     title: 'Cards Agianst Humanity',
    //     thumb: 'https://i.imgur.com/024uvId.jpg',
    //     link: 'https://www.cardsagainsthumanity.online/',
    //     image: 'https://i.imgur.com/q9qNfp9.jpg',
    //     info: 'Browser, Zwischendurch',
    //     color: '#000000',
    // },
    mw2: {
        title: 'Call Of Duty: Modern Warfare 2',
        thumb: 'https://i.imgur.com/5eYbMq2.jpg',
        image: 'https://i.imgur.com/sLhOKfW.jpg',
        link: '',
        info: 'Team Deathmatch, Gungame, Fun Mods',
        color: '#9cee86',
    },
    jk2: {
        title: 'STAR WARS Jedi Knight II - Jedi Outcast',
        thumb: 'https://i.imgur.com/k8kxGTk.jpg',
        image: 'https://i.imgur.com/0Alp8bp.jpg',
        link: '',
        info: 'Oldschool Fun Arena Deathmatch',
        color: '#67a7f0',
    },
    l4d2: {
        title: 'Left 4 Dead 2',
        thumb: 'https://i.imgur.com/KuuQ1GT.jpg',
        image: 'https://i.imgur.com/WaIrMKD.jpg',
        link: 'steam://store/550',
        info: 'Coop Survival / Versus',
        color: '#7aa60f',
    },
    // d2: {
    //     title: 'Divinity 2',
    //     thumb: 'https://i.imgur.com/qxka1Gx.jpg',
    //     link: 'steam://store/435150',
    //     image: 'https://i.imgur.com/GZBy4wP.jpg',
    //     info: 'Fun Run',
    //     color: '#e6071e',
    // },
    dbd: {
        title: 'Dead By Daylight',
        thumb: 'https://i.imgur.com/jXR8Nj8.jpg',
        image: 'https://i.imgur.com/ke7KphW.jpg',
        link: 'steam://store/381210',
        info: '2v1 Casual',
        color: '#ffffff',
    },
    aoe: {
        title: 'Age Of Empires 2 (HD 2013)',
        thumb: 'https://i.imgur.com/FCFp0RP.jpg',
        image: 'https://i.imgur.com/YTTGmZK.jpg',
        link: 'steam://store/221380',
        info: '1v1 Turnier, Versus',
        color: '#fe201c',
    },
    sc: {
        title: 'Stronghold Crusader HD',
        thumb: 'https://i.imgur.com/w237qpy.jpg',
        image: 'https://i.imgur.com/hBObbkX.jpg',
        link: 'steam://store/40970',
        info: 'Casual Versus',
        color: '#b9a094',
    },
    mc: {
        title: 'Minecraft',
        thumb: 'https://i.imgur.com/Jv2mpCW.jpg',
        image: 'https://i.imgur.com/1fc48il.jpg',
        link: 'https://www.minecraft.net',
        info: 'Klötzchenspaß für Zwischendurch',
        color: '#5fa036',
    },
    wow: {
        title: 'World of Warcraft',
        thumb: 'https://i.imgur.com/ycqGUMQ.jpg',
        image: 'https://i.imgur.com/EU9fzIM.jpg',
        link: 'https://worldofwarcraft.com/',
        info: 'Leveln, Mythics, Raiden, Mounts farmen',
        color: '#4c5d6f',
    },
};
